"""create MVP course data schema

Revision ID: b1813416469a
Revises: 
Create Date: 2026-08-02 16:36:23.704675
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b1813416469a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_successful_import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_academic_terms_valid_date_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_terms')),
    sa.UniqueConstraint('source_identifier', name=op.f('uq_academic_terms_source_identifier'))
    )
    op.create_index('ix_academic_terms_published', 'academic_terms', ['is_published'], unique=False, postgresql_where=sa.text('is_published = true'))
    op.create_table('component_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('canonical_kind', sa.Enum('lecture', 'lab', 'recitation', 'other', name='canonical_component_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_types')),
    sa.UniqueConstraint('code', name=op.f('uq_component_types_code'))
    )
    op.create_table('instructors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instructors'))
    )
    op.create_index('ix_instructors_normalized_name', 'instructors', ['normalized_name'], unique=False)
    op.create_index('uq_instructors_source_identifier', 'instructors', ['source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('subjects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    op.create_index('uq_subjects_source_identifier', 'subjects', ['source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('course_number', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_courses_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('subject_id', 'course_number', name=op.f('uq_courses_subject_id'))
    )
    op.create_index('ix_courses_title_lower', 'courses', [sa.literal_column('lower(title)')], unique=False)
    op.create_index('uq_courses_source_identifier', 'courses', ['source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('import_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='import_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_term_identifier', sa.String(length=64), nullable=False),
    sa.Column('source_data_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixture_name', sa.String(length=255), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_deactivated', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('warning_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'running' OR completed_at IS NOT NULL", name=op.f('ck_import_runs_completed_when_finished')),
    sa.CheckConstraint('records_deactivated IS NULL OR records_deactivated >= 0', name=op.f('ck_import_runs_records_deactivated_nonnegative')),
    sa.CheckConstraint('records_inserted IS NULL OR records_inserted >= 0', name=op.f('ck_import_runs_records_inserted_nonnegative')),
    sa.CheckConstraint('records_read IS NULL OR records_read >= 0', name=op.f('ck_import_runs_records_read_nonnegative')),
    sa.CheckConstraint('records_rejected IS NULL OR records_rejected >= 0', name=op.f('ck_import_runs_records_rejected_nonnegative')),
    sa.CheckConstraint('records_updated IS NULL OR records_updated >= 0', name=op.f('ck_import_runs_records_updated_nonnegative')),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], name=op.f('fk_import_runs_academic_term_id_academic_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs'))
    )
    op.create_index(op.f('ix_import_runs_source_checksum'), 'import_runs', ['source_checksum'], unique=False)
    op.create_index('ix_import_runs_term_started', 'import_runs', ['academic_term_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_import_runs_term_status_completed', 'import_runs', ['academic_term_id', 'status', sa.literal_column('completed_at DESC')], unique=False)
    op.create_foreign_key(
        'fk_academic_terms_last_successful_import_run_id_import_runs',
        'academic_terms',
        'import_runs',
        ['last_successful_import_run_id'],
        ['id'],
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('title_override', sa.String(length=255), nullable=True),
    sa.Column('minimum_credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('maximum_credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('relationship_data_status', sa.Enum('not_applicable', 'complete', 'partial', 'unknown', name='relationship_data_status', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], name=op.f('fk_course_offerings_academic_term_id_academic_terms')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offerings_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings')),
    sa.UniqueConstraint('academic_term_id', 'course_id', name=op.f('uq_course_offerings_academic_term_id'))
    )
    op.create_index('uq_course_offerings_term_source', 'course_offerings', ['academic_term_id', 'source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('offering_components',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('component_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_code', sa.String(length=40), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('minimum_required', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('maximum_allowed', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('selection_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maximum_allowed >= minimum_required', name=op.f('ck_offering_components_valid_selection_range')),
    sa.CheckConstraint('minimum_required >= 0', name=op.f('ck_offering_components_minimum_required_nonnegative')),
    sa.CheckConstraint('selection_order >= 0', name=op.f('ck_offering_components_selection_order_nonnegative')),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_types.id'], name=op.f('fk_offering_components_component_type_id_component_types')),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_offering_components_course_offering_id_course_offerings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offering_components')),
    sa.UniqueConstraint('course_offering_id', 'component_type_id', 'source_code', name=op.f('uq_offering_components_course_offering_id'))
    )
    op.create_table('sections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('offering_component_id', sa.BigInteger(), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('crn', sa.String(length=32), nullable=True),
    sa.Column('section_code', sa.String(length=32), nullable=False),
    sa.Column('source_component_code', sa.String(length=40), nullable=True),
    sa.Column('instruction_method', sa.String(length=80), nullable=True),
    sa.Column('campus', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'canceled', 'closed', 'unknown', name='section_status', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('first_seen_import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('inactive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_active AND inactive_at IS NULL) OR (NOT is_active AND inactive_at IS NOT NULL)', name=op.f('ck_sections_active_matches_inactive_at')),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], name=op.f('fk_sections_academic_term_id_academic_terms')),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_sections_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['first_seen_import_run_id'], ['import_runs.id'], name=op.f('fk_sections_first_seen_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['last_seen_import_run_id'], ['import_runs.id'], name=op.f('fk_sections_last_seen_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['offering_component_id'], ['offering_components.id'], name=op.f('fk_sections_offering_component_id_offering_components')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('course_offering_id', 'offering_component_id', 'section_code', name=op.f('uq_sections_course_offering_id'))
    )
    op.create_index('ix_sections_component_active', 'sections', ['offering_component_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sections_last_seen_import_run_id'), 'sections', ['last_seen_import_run_id'], unique=False)
    op.create_index('ix_sections_offering_active', 'sections', ['course_offering_id', 'is_active'], unique=False)
    op.create_index('ix_sections_term_active', 'sections', ['academic_term_id', 'is_active'], unique=False)
    op.create_index('uq_sections_term_crn', 'sections', ['academic_term_id', 'crn'], unique=True, postgresql_where=sa.text('crn IS NOT NULL'))
    op.create_index('uq_sections_term_source', 'sections', ['academic_term_id', 'source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('meeting_times',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('meeting_type', sa.String(length=40), server_default='class', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='America/New_York', nullable=False),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('is_asynchronous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_arranged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)', name=op.f('ck_meeting_times_valid_time_range')),
    sa.CheckConstraint('NOT (is_asynchronous AND is_arranged)', name=op.f('ck_meeting_times_single_special_meeting_kind')),
    sa.CheckConstraint('NOT (is_asynchronous OR is_arranged) OR (start_time IS NULL AND end_time IS NULL)', name=op.f('ck_meeting_times_untimed_special_meeting')),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_meeting_times_valid_date_range')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_meeting_times_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_times')),
    sa.UniqueConstraint('section_id', 'source_fingerprint', name=op.f('uq_meeting_times_section_id'))
    )
    op.create_index('ix_meeting_times_section_dates', 'meeting_times', ['section_id', 'start_date', 'end_date'], unique=False)
    op.create_index('uq_meeting_times_section_source', 'meeting_times', ['section_id', 'source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('section_instructors',
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('instructor_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_section_instructors_display_order_nonnegative')),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name=op.f('fk_section_instructors_instructor_id_instructors')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_section_instructors_section_id_sections')),
    sa.PrimaryKeyConstraint('section_id', 'instructor_id', name=op.f('pk_section_instructors'))
    )
    op.create_index('ix_section_instructors_instructor_id', 'section_instructors', ['instructor_id'], unique=False)
    op.create_table('section_relationship_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('source_section_id', sa.BigInteger(), nullable=False),
    sa.Column('target_component_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_type', sa.Enum('requires_one_of', 'compatible_only', name='relationship_rule_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('is_authoritative', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_section_relationship_rules_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['source_section_id'], ['sections.id'], name=op.f('fk_section_relationship_rules_source_section_id_sections')),
    sa.ForeignKeyConstraint(['target_component_id'], ['offering_components.id'], name=op.f('fk_section_relationship_rules_target_component_id_offering_components')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_relationship_rules')),
    sa.UniqueConstraint('source_section_id', 'target_component_id', 'rule_type', name=op.f('uq_section_relationship_rules_source_section_id'))
    )
    op.create_index('ix_section_relationship_rules_offering_section', 'section_relationship_rules', ['course_offering_id', 'source_section_id'], unique=False)
    op.create_index('uq_section_relationship_rules_offering_source', 'section_relationship_rules', ['course_offering_id', 'source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.create_table('meeting_days',
    sa.Column('meeting_time_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_meeting_days_valid_day_of_week')),
    sa.ForeignKeyConstraint(['meeting_time_id'], ['meeting_times.id'], name=op.f('fk_meeting_days_meeting_time_id_meeting_times')),
    sa.PrimaryKeyConstraint('meeting_time_id', 'day_of_week', name=op.f('pk_meeting_days'))
    )
    op.create_index('ix_meeting_days_day_meeting', 'meeting_days', ['day_of_week', 'meeting_time_id'], unique=False)
    op.create_table('section_relationship_options',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('target_section_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['section_relationship_rules.id'], name=op.f('fk_section_relationship_options_rule_id_section_relationship_rules')),
    sa.ForeignKeyConstraint(['target_section_id'], ['sections.id'], name=op.f('fk_section_relationship_options_target_section_id_sections')),
    sa.PrimaryKeyConstraint('rule_id', 'target_section_id', name=op.f('pk_section_relationship_options'))
    )
    op.create_index('ix_section_relationship_options_target_section_id', 'section_relationship_options', ['target_section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_section_relationship_options_target_section_id', table_name='section_relationship_options')
    op.drop_table('section_relationship_options')
    op.drop_index('ix_meeting_days_day_meeting', table_name='meeting_days')
    op.drop_table('meeting_days')
    op.drop_index('uq_section_relationship_rules_offering_source', table_name='section_relationship_rules', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('ix_section_relationship_rules_offering_section', table_name='section_relationship_rules')
    op.drop_table('section_relationship_rules')
    op.drop_index('ix_section_instructors_instructor_id', table_name='section_instructors')
    op.drop_table('section_instructors')
    op.drop_index('uq_meeting_times_section_source', table_name='meeting_times', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('ix_meeting_times_section_dates', table_name='meeting_times')
    op.drop_table('meeting_times')
    op.drop_index('uq_sections_term_source', table_name='sections', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('uq_sections_term_crn', table_name='sections', postgresql_where=sa.text('crn IS NOT NULL'))
    op.drop_index('ix_sections_term_active', table_name='sections')
    op.drop_index('ix_sections_offering_active', table_name='sections')
    op.drop_index(op.f('ix_sections_last_seen_import_run_id'), table_name='sections')
    op.drop_index('ix_sections_component_active', table_name='sections')
    op.drop_table('sections')
    op.drop_table('offering_components')
    op.drop_index('uq_course_offerings_term_source', table_name='course_offerings', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_table('course_offerings')
    op.drop_index('ix_import_runs_term_status_completed', table_name='import_runs')
    op.drop_index('ix_import_runs_term_started', table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_source_checksum'), table_name='import_runs')
    op.drop_constraint(
        'fk_academic_terms_last_successful_import_run_id_import_runs',
        'academic_terms',
        type_='foreignkey',
    )
    op.drop_table('import_runs')
    op.drop_index('uq_courses_source_identifier', table_name='courses', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('ix_courses_title_lower', table_name='courses')
    op.drop_table('courses')
    op.drop_index('uq_subjects_source_identifier', table_name='subjects', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_table('subjects')
    op.drop_index('uq_instructors_source_identifier', table_name='instructors', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('ix_instructors_normalized_name', table_name='instructors')
    op.drop_table('instructors')
    op.drop_table('component_types')
    op.drop_index('ix_academic_terms_published', table_name='academic_terms', postgresql_where=sa.text('is_published = true'))
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
